### ISSUE TITLE
Support symlinks

### ISSUE THREAD

**Issue by ypid** [debops/ansible-persistent_paths#5]
Ref: https://github.com/debops/ansible-persistent_paths/pull/4

**Comment by ypid** [comment]
Looking around in the Ansible docs I found that the [template module](https://docs.ansible.com/ansible/template_module.html) has an option `unsafe_writes` which allows to update bind mounted files in place. So this sounds like the best option.

@drybjed I guess something like:

```YAML
unsafe_writes : '{{ ansible__unsafe_writes|d() }}'
```

would need to be added to file related tasks in roles to make them fully work on Qubes OS. At least no file prefix anymore. Does that sound acceptable?

**Comment by drybjed** [comment]
Yes, I agree that this option is better, epseically that the `copy` module has a similar one.

I'm not sure where `ansible__unsafe_writes` variable orginates from, I guess Ansible local facts would be the cleanest option? I think something like:

```yaml
- template:
    src: 'etc/motd.j2'
    dest: '/etc/motd'
    unsafe_writes: '{{ True if ansible_local|d(0 and ansible_local.core|d() and
                       ansible_local.core.unsafe_writes|d() else omit }}'
```

I think that this might be useful with more cases than just Qubes OS, so putting this option in `debops.core` sounds best to me. What do you think?
